<div class="Container-fluid">
    <div class="col-12 mt-4">
        <div class="row">
            <div class="usuario col-md-4 bg-white">
                <h5><?= $_SESSION['email'] ?></h5>
                <div class="information ">
                    produtos: <?= count($this->view->empresa) ?>
                </div>
            </div>

            <div class="col-md-8">
                <div class="py-3">
                    <button class="btn btn-add w-100" data-toggle="modal" data-target="#form-modal">Adicionar Produto</button>
                </div>
            </div>

        </div>
        <!-- produtos -->
        <div class="col mt-4">
            <div class="container">
                <div class="pesquisa">
                    <div class="form-group input-group">
        
                        <label class="btn"><i class="fa fa-search" aria-hidden="true"></i></label>
                        <input name="consulta" id="txt_consulta" placeholder="Consultar" type="text" class="form-control">
                    </div>
                </div>
                <div class="produtos w-100 row p-0">

                    <?php foreach ($this->view->empresa as $p) { ?>
                        <!-- cards -->

                        <div class="card col-md-4 my-4 ml-2 box-b" id="produtos">
                            <div class="d-flex justify-content-center align-items-center">
                                <img class="card-img-top" src="img/produtos/<?= $p['img'] ?>" alt="img" style="width:200px;height:200px">
                            </div>
                            <div class="card-body">
                                <h6 class="bold"><?= $p['nome'] ?></h>
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">local de entrega: <?= $p['local_coleta'] ?></li>
                                <li class="list-group-item">validade: <?= date('d/m/Y', strtotime($p['data_validade'])) ?></li>
                                <li class="list-group-item">Status:
                                    <?php if ($p['id_status'] == 0) {
                                        echo "Pendente";
                                    } else {
                                        echo "Concluído";
                                    } ?>
                                </li>
                            </ul>
                            <div class="card-body row">
                                <a data-toggle="modal" data-target="#modal-edit-<?= $p['id_alimento'] ?>" class="btn btn-primary text-light col-md">Editar</a>
                                <a href="excluir_produto?id=<?= $p['id_alimento'] ?>" class="btn btn-danger col-md">Excluir</a>
                            </div>
                        </div>

                        <!-- Modal de editar-->
                        <div class="modal fade" id="modal-edit-<?= $p['id_alimento'] ?>" tabindex="-1" role="dialog" aria-labelledby="title" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered" role="document">
                                <div class="modal-content border-0">
                                    <div class="modal-header text-center align-items-center">
                                        <h4 class="modal-title font-weight-bold text-secondary">Editar produto</h4>
                                        <button type="button" class="close border-0" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <form action="/edita_produto" method="post" enctype="multipart/form-data">
                                        <div class="modal-body py-4">
                                            <div class=" card-body border-0 pt-0">
                                                <div class="d-flex justify-content-center ">
                                                    <img src="img/produtos/<?= $p['img'] ?>" alt="edit" style="max-width: 150px;border-radius:100%">
                                                </div>
                                                <div class="label-float">
                                                    <label>Nome do produto</label>
                                                    <input type="text" name="nome" value="<?= $p['nome'] ?>" class=" form-control" size="60" maxlength="60" placeholder="Nome" required>
                                                </div>

                                                <div class="label-float mt-3">
                                                    <label>Local de entrega</label>
                                                    <input type="text" name="local" value="<?= $p['local_coleta'] ?>" class=" form-control" size="90" placeholder="Local de entrega" required>
                                                </div>

                                                <div class="label-float mt-3">
                                                    <label>Data de validade</label>
                                                    <input type="Date" value="<?= $p['data_validade'] ?>" name="validade" class="form-control" required>
                                                </div>

                                                <div class="label-float mt-3">
                                                    <label>Imagem do produto</label>
                                                    <input class="form-control-file" type="file" name="img" value="<?= $p['img'] ?>" required>
                                                </div>

                                                <input type="hidden" name="id" value="<?= $p['id_alimento'] ?>">
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="submit" class="btn btn-primary w-100 text-light">Editar</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>

                    <?php } ?>
                </div>
            </div>
        </div>


    </div>
</div>


<!-- Modal de registro-->
<div class="modal fade" id="form-modal" tabindex="-1" role="dialog" aria-labelledby="title" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content border-0">
            <div class="modal-header text-center align-items-center">
                <h4 class="modal-title font-weight-bold text-secondary">Registrar produto</h4>
                <button type="button" class="close border-0" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="/registra_produto" method="post" enctype="multipart/form-data">
                <div class="modal-body py-4">
                    <div class=" card-body border-0 pt-0">
                        <div class="label-float">
                            <label>Nome do produto</label>
                            <input type="text" name="nome" class=" form-control" size="60" maxlength="60" placeholder="Nome" required>
                        </div>

                        <div class="label-float mt-3">
                            <label>Local de entrega</label>
                            <input type="text" name="local" class=" form-control" size="90" placeholder="Local de entrega" required>
                        </div>

                        <div class="label-float mt-3">
                            <label>Data de validade</label>
                            <input type="Date" name="validade" class="form-control" required>
                        </div>

                        <div class="label-float mt-3">
                            <label>Imagem do produto</label>
                            <input class="form-control" type="file" name="img" id="img" required>
                        </div>

                        <input type="hidden" name="id" value="<?= $_SESSION['id'] ?>">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary w-100 text-light">Registrar</button>
                </div>
            </form>
        </div>
    </div>
</div>