<div class="home col-12 container bg-light">
    <div class="row">

        <img src="../img/bg/contato.png" alt="" class="img-home col-sm-6">


        <div class="col-sm-6 pt-2">
            <div class="py-5">
                <h1 class="t-1 pb-2">Entre em contato</h1>
                <form action="" class="row">
                    <div class="col-md-12">
                        <label for="">nome</label>
                        <input type="text" placeholder="nome" class="form-control">
                    </div>

                    <div class="col-md-12">
                        <label for="">email</label>
                        <input type="email" placeholder="email" class="form-control" required>
                    </div>

                    <div class="col-md-12">
                        <label for="">assunto</label>
                        <input type="text" placeholder="assunto" class="form-control">
                    </div>

                    <div class="col-md-12">
                        <label for="">mensagem</label>
                        <textarea name="" id="" cols="30" rows="5" class="form-control" placeholder="mensagem..."></textarea>
                    </div>

                    <button class="btn btn-register text-white w-100 m-2">Enviar</button>
                </form>
            </div>
        </div>
    </div>
</div>