<div class="home col-12 container bg-light">
    <div class="row">
        <img src="../img/bg/home.png" alt="" class="img-home col-sm-6">

        <div class="col-sm-6 pt-5">
            <div class="py-5">
                <h1 class="t-1 pb-2">Especializado em coleta e distribuição de alimentos</h1>
                <p class="pb-2">Empresas de alimentos colocam os produtos e entregadores recebem a demanda! entre!</p>
                <div class="botoes">
                    <a href="login" class="btn btn-danger btn-home">Empresa</a>
                    <a href="login" class="btn btn-outline-danger btn-home">Entregador</a>
                </div>
            </div>
        </div>
    </div>
</div>