<div class="row m-auto">
    <div class="panel-img col-xl-6 d-xl-inline-block d-none"></div>
    <div class="panel-login col-xl-6 col-12 d-flex align-items-center">
        <div class="login-box m-auto">
            <h2 class="title text-secondary text-center">Entre ou cadastre-se</h2>
            <form action="/autenticacao" method="post">
                <div class="label-float mt-4">
                    <label>E-mail</label>
                    <input type="email" name="email" class="form-custom form-control mt-1 bg-transparent input-login" size="60" maxlength="60" placeholder="E-mail" required>
                </div>
                <div class="label-float mt-4">
                    <label>Senha</label>
                    <input type="password" name="senha" class="form-custom form-control mt-1 bg-transparent input-login" size="60" maxlength="15" placeholder="Senha" required>
                </div>
                <button type="submit" class="btn btn-register text-white w-100 mt-4">Entrar</button>

                <a href="/cadastro" class="mt-2 d-block register-link">Ainda não possui cadastro, Entregador clique aqui</a>
                <a href="/empresa" class="mt-2 d-block register-link"> Empresa clique aqui</a>
            </form>
        </div>
    </div>
</div>