<div class="home col-12 container bg-light">
    <div class="row">

        <img src="../img/bg/empresa.png" alt="" class="img-home col-sm-6">


        <div class="col-sm-6 pt-5">
            <div class="py-5">
                <h1 class="t-1 pb-2">Especializado em coleta e distribuição de alimentos</h1>
                <p class="pb-2">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio quos ea pariatur est aspernatur neque nisi labore? Commodi numquam quaerat, quisquam optio ea quia id iste omnis distinctio in magnam. Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur aliquid natus aliquam suscipit earum consectetur, fuga numquam asperiores, repellendus iure repellat delectus inventore dolorem temporibus, aspernatur ut maiores consequuntur a.!</p>
                
            </div>
        </div>
    </div>
</div>